spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vote-api
    password: 136279804
    username: pedro

  jpa:
    hibernate:
      ddl-auto: update